In [1]:
#BY:MAKAYLA JEAN-BAPTISTE
#rename numpy 
import numpy as np

In [25]:
# question 1 Creating matrices 
mat1= np.array([[2,-14,8],[2,5,3]])
mat2= np.array([[8,5,1],[6,10,-3]])
print(mat1)
print(mat2)

[[  2 -14   8]
 [  2   5   3]]
[[ 8  5  1]
 [ 6 10 -3]]


In [26]:
# solution of  matrices 
sol=np.multiply(mat1,mat2)
print(sol)

[[ 16 -70   8]
 [ 12  50  -9]]


In [27]:
#question 2 scalar product of a constant and matrix

In [28]:
#multipling matrix by -2
array1=np.array([[-5,2,4],[6,10,-3],[-12,7,-2]])
n=-2
print(array1)

[[ -5   2   4]
 [  6  10  -3]
 [-12   7  -2]]


In [29]:
#solution
sol=np.multiply(array1,n)
print(sol)

[[ 10  -4  -8]
 [-12 -20   6]
 [ 24 -14   4]]


In [30]:
# question 3 fid the determinant

In [31]:
#create matrices
array1= np.array([[2, -14,8],[2,5,3],[5,10,6]])
array2= np.array([[8,5,7,9],[-2,12,6,6],[7,15,2,3],[5,-7,1,4]])
print(array1)
print(array2)

[[  2 -14   8]
 [  2   5   3]
 [  5  10   6]]
[[ 8  5  7  9]
 [-2 12  6  6]
 [ 7 15  2  3]
 [ 5 -7  1  4]]


In [32]:
#calculating the determinant of matrix
det1=(np.linalg.det(array1))
det2=(np.linalg.det(array2))
print(int(det1))
print(det2)

-81
-2026.0
