In [1]:
#By:makayla jean-baptiste
#rename numpy
import numpy as np

In [3]:
#question 1 12x+3y=162 and 8x3y=122
A= np.array([[12,3],[8,3]])
B= np.array([[162],[122]])

In [4]:
#verify the size of the matrices and right hand side vector
print('dim. of matrix A = ', A.shape)
print('dim. of vector B = ', B.shape)

dim. of matrix A =  (2, 2)
dim. of vector B =  (2, 1)


In [5]:
#find the det(A)!=0
np.linalg.det(A)

12.0

In [6]:
#find inverse of A
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 0.25       -0.25      ]
 [-0.66666667  1.        ]]


In [7]:
#finding solution
sol= inv_A.dot(B)
print(sol)

[[10.]
 [14.]]


In [8]:
#question 2 x+y=6 and 6x+3y=30
A= np.array([[1,1],[6,3]])
B= np.array([[6],[30]])

In [9]:
#verify the size of the matrices and right hand side vector
print('dim. of matrix A = ', A.shape)
print('dim. of vector B = ', B.shape)


dim. of matrix A =  (2, 2)
dim. of vector B =  (2, 1)


In [10]:
#find the det(A)!=0
np.linalg.det(A)

-2.9999999999999996

In [11]:
#find inverse of A
inv_A = np.linalg.inv(A)
print(inv_A)

[[-1.          0.33333333]
 [ 2.         -0.33333333]]


In [12]:
#finding solution
sol= inv_A.dot(B)
print(sol)

[[4.]
 [2.]]


In [13]:
#question3 x+y+z=12000, -y+z=4000, 0.03x+0.04y+0.07z=670
'dtype=object'
A= np.array([[1,1,1],[-1,1,0],[0.03,0.04,0.07]])
B=  np.array ([[12000],[4000],[670]])

In [14]:
#verify the size of the matrices and right hand side vector
print('dim. of matrix A = ', A.shape)
print('dim. of vector B = ', B.shape)


dim. of matrix A =  (3, 3)
dim. of vector B =  (3, 1)


In [15]:
#find the det(A)!=0
np.linalg.det(A)

0.07

In [16]:
#find inverse of A
inv_A = np.linalg.inv(A)
print(inv_A)

[[  1.          -0.42857143 -14.28571429]
 [  1.           0.57142857 -14.28571429]
 [ -1.          -0.14285714  28.57142857]]
